name: Run Python Script

on:
  workflow_dispatch:
    

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
    
        - name: get ip
          run: |
            ifconfig eth0 | grep -oP 'inet \K[\d.]+'

            

